# Generated by Django 4.2.7 on 2024-01-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymodel',
            new_name='Materials',
        ),
    ]
