# Generated by Django 4.2.7 on 2024-01-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_rename_mymodel_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='purpose',
            new_name='name',
        ),
    ]
